using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace ErrorMessagesAPI
{
    public class Message
    {
        //[BsonId]
        // standard BSonId generated by MongoDb
        //public ObjectId InternalId { get; set; }
        /// <summary>
        /// Message Id
        /// </summary>
        /// 
        [BsonId]
        public ObjectId InternalId { get; set; }
        public long Id { get; set; }



        /// <summary>
        /// Message Text
        /// </summary>
        /// 
        [BsonElement("text")]
        public string TextMessage { get; set; }

        /// <summary>
        /// Message creation datetime
        /// </summary>
        /// 
        [BsonElement("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Message Upate datetime
        /// </summary>
        ///  
        [BsonElement("updatedAt")]
        public DateTime UpdatedAt { get; set; }

    }
}


